version: '2.1'
services:
  knit_server:
    build: 
      context: .
      dockerfile: docker/knit_server/Dockerfile    
    container_name: knit_server
    volumes:
      - ./app:/app
      - static:/static
    command:  > 
        bash -c "
            python /app/manage.py collectstatic --no-input
            python /app/manage.py makemigrations users
            python /app/manage.py makemigrations products
            python /app/manage.py migrate
            gunicorn --chdir /app/ --bind :8000 knit_server.wsgi
          "
    ports:
      - 8000:8000
    networks: 
      - app-network
  nginx:
      build: 
        context: .
        dockerfile: docker/nginx/Dockerfile
      ports:
        - "80:80"
      container_name: knit_nginx    
      volumes:
        - ./app:/app
        - static:/static
      depends_on:
        - knit_server
      networks: 
        - app-network
    
#Docker Networks
networks:
  app-network:
    driver: bridge

#Docker Volumes
volumes:
  static:
