# Generated by Django 3.0.1 on 2020-04-09 12:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import users.kmodels.image_model
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('username', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True)),
                ('password', models.CharField(max_length=128)),
                ('is_admin', models.IntegerField(blank=True, default=False, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'user',
                'ordering': ['-created_at', '-updated_at'],
                'managed': True,
            },
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='KAddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(default='', max_length=50)),
                ('address_line_2', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('landmark', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('postalCode', models.IntegerField(default=None)),
                ('latitude', models.FloatField(blank=True, default=None, max_length=20, null=True)),
                ('longitude', models.FloatField(blank=True, default=None, max_length=20, null=True)),
                ('geoAddress', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('city', models.CharField(max_length=25, null=True)),
                ('state', models.CharField(blank=True, default=None, max_length=25, null=True)),
                ('country', models.CharField(blank=True, default=None, max_length=45, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
            options={
                'verbose_name': 'Knit Address',
                'verbose_name_plural': 'Knit Addresses',
                'db_table': 'knit_address',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(default=None, max_length=254, upload_to=users.kmodels.image_model.nameFile)),
                ('source', models.CharField(blank=True, default='customer', max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'knit_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='KUserType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'Knit User type',
                'verbose_name_plural': 'Knit User types',
                'db_table': 'knit_user_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('firstName', models.TextField(blank=True)),
                ('lastName', models.TextField(blank=True)),
                ('gender', models.IntegerField(blank=True, default=None, null=True)),
                ('married', models.BooleanField(default=False)),
                ('birthday', models.DateTimeField(blank=True, default=None, null=True)),
                ('anniversary', models.DateTimeField(blank=True, default=None, null=True)),
                ('user_role', models.CharField(blank=True, default=None, max_length=80, null=True)),
                ('image', models.URLField(blank=True)),
                ('address', models.ManyToManyField(to='users.KAddress')),
                ('images', models.ManyToManyField(to='users.KImage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('userTypes', models.ManyToManyField(to='users.KUserType')),
            ],
            options={
                'ordering': ['-created_at', '-updated_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KVendorUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default=None, max_length=80, null=True)),
                ('openTime', models.TimeField(blank=True, default=datetime.time(9, 30), null=True)),
                ('closeTime', models.TimeField(blank=True, default=datetime.time(21, 0), null=True)),
                ('masters', models.IntegerField(blank=True, default=None, null=True)),
                ('isWeekends', models.BooleanField(blank=True, default=False, null=True)),
                ('alternateDays', models.CharField(blank=True, max_length=80, null=True)),
                ('closed', models.BooleanField(default=False)),
                ('emergency', models.BooleanField(default=False)),
                ('doorService', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True, max_length=180)),
                ('images', models.ManyToManyField(blank=True, default=None, to='users.KImage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'knit_vendor_user',
                'managed': True,
            },
        ),
    ]
