# Generated by Django 3.0.1 on 2020-03-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bio',
            new_name='firstName',
        ),
        migrations.AddField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.KAddress'),
        ),
        migrations.AddField(
            model_name='profile',
            name='anniversary',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.KImage'),
        ),
        migrations.AddField(
            model_name='profile',
            name='isMarried',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='lastName',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_role',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='user_type',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.KUserType'),
        ),
    ]
