# Generated by Django 3.0.1 on 2020-04-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female'), (3, 'Trans Gender')], default=None, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_role',
            field=models.IntegerField(blank=True, choices=[(1, 'Customer'), (2, 'Super Admin'), (3, 'Admin'), (4, 'Manager'), (5, 'Developer'), (6, 'Owner'), (7, 'Sales Manger'), (8, 'Delivery')], default=1, null=True),
        ),
    ]
