# Generated by Django 3.0.1 on 2020-05-09 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_vendor_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='userTypes',
            field=models.ManyToManyField(blank=True, default=None, to='users.UserType'),
        ),
    ]
