# Generated by Django 3.0.1 on 2020-04-12 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200411_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='closeTime',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='openTime',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
