# Generated by Django 3.0.1 on 2020-03-24 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191224_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, choices=[('USER', 'USER'), ('ADMIN', 'ADMIN'), ('LEADER', 'LEADER'), ('SUPER_ADMIN', 'SUPER ADMIN'), ('GUEST', 'GUEST'), ('DEL_BOY', 'DELIVERY BOY')], default='GUEST', max_length=80, null=True),
        ),
    ]
