# Generated by Django 3.0.1 on 2020-03-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200324_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvendoruser',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='kvendoruser',
            name='is_weekdays',
        ),
        migrations.RemoveField(
            model_name='kvendoruser',
            name='start_time',
        ),
        migrations.AddField(
            model_name='kvendoruser',
            name='close_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='kvendoruser',
            name='is_door_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kvendoruser',
            name='open_time',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='kvendoruser',
            name='alternate_days',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
