# Generated by Django 3.0.1 on 2020-03-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200328_1157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='alternate_days',
            new_name='alternateDays',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='close_time',
            new_name='closeTime',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='is_door_service',
            new_name='closed',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='is_emergency_available',
            new_name='doorService',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='is_open',
            new_name='emergency',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='is_weekends',
            new_name='isWeekends',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='masters_count',
            new_name='mastersCount',
        ),
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='open_time',
            new_name='openTime',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='isMarried',
            new_name='married',
        ),
        migrations.AddField(
            model_name='kvendoruser',
            name='description',
            field=models.TextField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='kvendoruser',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.KImage'),
        ),
        migrations.AddField(
            model_name='kvendoruser',
            name='userTypes',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.KUserType'),
        ),
        migrations.AlterField(
            model_name='kvendoruser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='kvendoruser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
