# Generated by Django 3.0.1 on 2020-03-28 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200328_1421'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kvendoruser',
            old_name='mastersCount',
            new_name='masters',
        ),
    ]
