# Generated by Django 3.0.1 on 2020-03-24 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200324_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='users.KAddress'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_role',
            field=models.CharField(blank=True, default=None, max_length=80, null=True),
        ),
    ]
