# Generated by Django 3.0.1 on 2020-03-24 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200324_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kvendoruser',
            name='address',
        ),
    ]
