# Generated by Django 3.0.1 on 2020-03-28 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200328_1502'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvendoruser',
            name='closeTime',
            field=models.TimeField(default=datetime.time(21, 0)),
        ),
        migrations.AlterField(
            model_name='kvendoruser',
            name='openTime',
            field=models.TimeField(default=datetime.time(9, 30)),
        ),
    ]
