# Generated by Django 3.0.1 on 2020-03-28 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20200328_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvendoruser',
            name='closeTime',
            field=models.TimeField(blank=True, default=datetime.time(21, 0), null=True),
        ),
        migrations.AlterField(
            model_name='kvendoruser',
            name='openTime',
            field=models.TimeField(blank=True, default=datetime.time(9, 30), null=True),
        ),
    ]
