# Generated by Django 3.0.1 on 2020-03-29 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200328_1547'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user_type',
            new_name='userTypes',
        ),
    ]
