# Generated by Django 3.0.1 on 2020-03-31 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200329_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='kaddress',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=45, null=True),
        ),
    ]
