# Generated by Django 3.0.1 on 2020-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200406_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kvendoruser',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='users.KImage'),
        ),
        migrations.AlterField(
            model_name='kvendoruser',
            name='userTypes',
            field=models.ManyToManyField(blank=True, default=None, to='users.KUserType'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ManyToManyField(to='users.KAddress'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='images',
            field=models.ManyToManyField(to='users.KImage'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='userTypes',
            field=models.ManyToManyField(to='users.KUserType'),
        ),
    ]
