# Generated by Django 3.0.1 on 2020-04-16 18:30

from django.db import migrations, models
import django.db.models.deletion
import products.kmodels.imagemodel


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(blank=True, choices=[('white', 'White'), ('black', 'Black'), ('green', 'Green'), ('red', 'Red'), ('purple', 'Purple'), ('brown', 'Brown'), ('violet', 'Violet')], default=None, max_length=80, null=True)),
            ],
            options={
                'db_table': 'ref_colors',
            },
        ),
        migrations.CreateModel(
            name='KImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=products.kmodels.imagemodel.uploadFolder)),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'knit_product_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(default=None, max_length=80, null=True)),
                ('offer_code', models.CharField(default=None, max_length=80, null=True, unique=True)),
                ('discount', models.CharField(default=None, max_length=120, null=True)),
                ('discount_type', models.CharField(blank=True, choices=[('rupees', 'Rupees'), ('percentage', 'Percentage')], default='percentage', max_length=80, null=True)),
                ('offer_from', models.DateTimeField()),
                ('offer_to', models.DateTimeField()),
                ('is_active', models.DateTimeField(default=False)),
            ],
            options={
                'verbose_name': 'Knit Offers',
                'db_table': 'knit_offers',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('xs', 'Xtra Small'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Xtra Large'), ('xxl', 'Double XL'), ('xxxl', 'Triple XL')], default=None, max_length=80, null=True)),
            ],
            options={
                'db_table': 'ref_sizes',
            },
        ),
        migrations.CreateModel(
            name='Stitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(default=None, max_length=80, null=True)),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=80, null=True)),
                ('images', models.ManyToManyField(blank=True, default=None, to='products.KImage')),
            ],
            options={
                'verbose_name': 'Knit Stitch Ref Table',
                'verbose_name_plural': 'Knit Stitch Ref Table',
                'db_table': 'knit_stitch',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StitchType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(default=None, max_length=80, null=True)),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=120, null=True)),
                ('images', models.ManyToManyField(blank=True, default=None, to='products.KImage')),
                ('stitch', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='products.Stitch')),
            ],
            options={
                'verbose_name': 'Knit Stitch Type Ref Table',
                'verbose_name_plural': 'Knit Stitch Type Ref Table',
                'db_table': 'knit_stitch_type',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StitchTypeDesign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('type', models.CharField(default=None, max_length=80, null=True)),
                ('code', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=120, null=True)),
                ('images', models.ManyToManyField(blank=True, default=None, to='products.KImage')),
                ('stitch_type', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.StitchType')),
            ],
            options={
                'verbose_name': 'Knit Stitch Type design',
                'verbose_name_plural': 'Knit Stitch Type design',
                'db_table': 'knit_stitch_type_design',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_by', models.IntegerField(blank=True, default=None, null=True)),
                ('title', models.CharField(default=None, max_length=80, null=True)),
                ('description', models.CharField(default=None, max_length=120, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('in_stock', models.BooleanField(blank=True, default=True, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('user', models.IntegerField(blank=True, null=True)),
                ('colors', models.ManyToManyField(blank=True, default=None, to='products.ColorModel')),
                ('images', models.ManyToManyField(blank=True, default=None, to='products.KImage')),
                ('offers', models.ManyToManyField(blank=True, default=None, to='products.Offers')),
                ('sizes', models.ManyToManyField(blank=True, default=None, to='products.SizeModel')),
                ('stitch', models.ManyToManyField(to='products.Stitch')),
                ('stitch_type', models.ManyToManyField(to='products.StitchType')),
                ('stitch_type_design', models.ManyToManyField(to='products.StitchTypeDesign')),
            ],
            options={
                'verbose_name': 'Knit Product',
                'verbose_name_plural': 'Knit Products',
                'db_table': 'knit_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=None, max_length=80, null=True)),
                ('actual_price', models.FloatField(blank=True, default=None, max_length=80)),
                ('discounted_price', models.FloatField(blank=True, default=None, max_length=80)),
                ('currency_type', models.CharField(blank=True, choices=[('R', 'Rupees'), ('$', 'Doller'), ('E', 'Euro')], default='R', max_length=80, null=True)),
                ('offers', models.ManyToManyField(to='products.Offers')),
            ],
            options={
                'db_table': 'knit_prices',
            },
        ),
        migrations.AddField(
            model_name='offers',
            name='stitch',
            field=models.ManyToManyField(to='products.Stitch'),
        ),
    ]
