# Generated by Django 3.0.1 on 2020-03-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='stitched_date',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True),
        ),
    ]
