# Generated by Django 3.0.1 on 2020-04-18 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offers',
            name='from_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offers',
            name='to_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
