# Generated by Django 3.0.1 on 2020-04-06 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='products.KImage'),
        ),
        migrations.AlterField(
            model_name='stitch',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='products.KImage'),
        ),
        migrations.AlterField(
            model_name='stitchtype',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='products.KImage'),
        ),
        migrations.AlterField(
            model_name='stitchtypedesign',
            name='images',
            field=models.ManyToManyField(blank=True, default=None, to='products.KImage'),
        ),
    ]
