# Generated by Django 3.0.1 on 2020-04-27 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stitchtype',
            name='description',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
