# Generated by Django 3.0.1 on 2020-04-17 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colormodel',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='colormodel',
            name='color',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
