# Generated by Django 3.0.1 on 2020-04-17 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200417_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizemodel',
            name='code',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='sizemodel',
            name='size',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
