# Generated by Django 3.0.1 on 2020-04-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200418_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('code', models.CharField(blank=True, default=None, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ref_materials',
            },
        ),
    ]
