version: '2.1'

services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./app:/app
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static
    depends_on:
      - knit_server
    networks: 
      - app-network
  knit_server:
    # image: mgurjala/knit_server_img:5.0
    build: 
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    command:  > 
        bash -c "
            python /app/manage.py collectstatic --no-input
            python /app/manage.py makemigrations users
            python /app/manage.py makemigrations products
            python /app/manage.py migrate
            gunicorn --chdir /app/ --bind :8000 knit_server.wsgi
          "
    ports:
      - 8000:8000
    networks: 
      - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge


# bash -c "
#             python /opt/services/djangoapp/src/manage.py makemigrations users
#             python /opt/services/djangoapp/src/manage.py makemigrations products
#             python /opt/services/djangoapp/src/manage.py migrate
#             gunicorn --chdir /opt/services/djangoapp/src/ --bind :8000 knit_server.wsgi
#           "

