# Generated by Django 3.0.1 on 2020-04-19 13:08

from django.db import migrations, models
import orders.kmodels.image_model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, max_length=254, null=True, upload_to=orders.kmodels.image_model.uploadFolder)),
                ('source', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('size', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'db_table': 'knit_orders_image',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProductOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_user', models.IntegerField(blank=True, default=None, null=True)),
                ('product_id', models.IntegerField(default=None, max_length=20, null=True)),
                ('details', models.CharField(default=None, max_length=180, null=True)),
            ],
            options={
                'db_table': 'knit_order_product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_user', models.IntegerField(blank=True, default=None, null=True)),
                ('duration', models.IntegerField(default=None, max_length=80, null=True)),
                ('details', models.CharField(default=None, max_length=180, null=True)),
                ('master_id', models.IntegerField(blank=True, default=None, null=True)),
                ('is_vfm', models.BooleanField(blank=True, default=False, null=True)),
                ('from_date', models.DateField(blank=True, null=True)),
                ('to_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'knit_order_master',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='StitchOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_user', models.IntegerField(blank=True, default=None, null=True)),
                ('updated_user', models.IntegerField(blank=True, default=None, null=True)),
                ('title', models.CharField(default=None, max_length=180, null=True)),
                ('details', models.CharField(default=None, max_length=180, null=True)),
                ('expected_date', models.DateField(blank=True, null=True)),
                ('emergency', models.BooleanField(blank=True, default=True, null=True)),
                ('stitch_id', models.IntegerField(default=None, max_length=20, null=True)),
                ('material_types', models.CharField(default=None, max_length=180, null=True)),
                ('is_vfm', models.BooleanField(blank=True, default=True, null=True)),
                ('images', models.ManyToManyField(blank=True, default=None, to='orders.OrderImage')),
            ],
            options={
                'db_table': 'knit_order_stich',
                'managed': True,
            },
        ),
    ]
