# Generated by Django 3.0.1 on 2020-04-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200419_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productorder',
            name='product_id',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='requestmaster',
            name='duration',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='stitchorder',
            name='stitch_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
